% This is an autogenerated sample test for file all
classdef tSimulatedModel < matlab.unittest.TestCase
    methods (Test)
        function testSimData(testCase)
            % Specify the input(s) of all
            sObj = SimulationModel;
            simulate(sObj);

            testCase.verifyClass(sObj.SimData, 'SimData')

            import matlab.unittest.constraints.IsSameSetAs
            testCase.verifyThat(sObj.SimData.DataNames,IsSameSetAs(["Drug","Receptor","Complex","RO"]));
        end
    end
end